spring:
    application:
        name: PizzaAPI
    http:
        encoding: UTF-8
        force: true
    datasource:
        initialize: true
        platform: hsqldb
    jpa:
        hibernate:
            ddl-auto: update

---

spring:
    profiles: dev

server:
    port: 9001

---

spring:
    profiles: prod

server:
    port: 9011
